general:
  model_name: streaming_TTS
  model_dir: models/Acoustic_model/improve/
  log_dir: logs/
  checkpoint_dir: checkpoints/
  streaming_mode: true
  model_weights: models/Acoustic_model/streaming_TTS_20260318-125822_verification
  saved_pred_dir: data/04-predictions/streaming/

data:
  raw_path: data/01-raw/LJSpeech/
  preprocessed_path: data/02-preprocessed/LJSpeech_dio
  feature_path: data/03-features/LJSpeech_dio
  data_dir: data/03-features/acoustic_dataset_norm_dio

  batch_size: 32
  shuffle_buffer: 10000

audio:
  n_mels: 80
  f0_pad_value: -20.0
  energy_pad_value: -20.0

model:
  vocab_size: auto
  embed_dim: 256
  encoder_dim: 256

  lstm_layers: 2
  lstm_dropout: 0.1
  cnn_kernel_size: 5
  cnn_dilations: [1, 2, 4]
  cnn_dropout: 0.1

  duration_predictor:
    filters: 256
    kernel_size: 6
    dropout: 0.2

  pitch_predictor:
    filters: 128
    kernel_size: 6
    dropout: 0.5

  energy_predictor:
    filters: 128
    kernel_size: 6
    dropout: 0.5

  postnet_layers: 7
  postnet_filters: 512
  postnet_kernel_size: 5
  postnet_dropout: 0.3

training:
  epochs: 200
  base_learning_rate: 0.0005

  optimizer:
    type: adam
    clipnorm: 1.0

  lr_schedule:
    type: cosine_decay
    alpha: 0.01

  early_stopping:
    monitor: loss
    patience: 100

loss:
  phase1:
    mel_weight: 1.0
    duration_weight: 0.1
    pitch_weight: 0.0
    energy_weight: 0.0
  phase2:
    mel_weight: 1.0
    duration_weight: 0.1
    pitch_weight: 0.05
    energy_weight: 0.05

  mel_components:
    l1: 0.5
    log: 0.5
    sc: 0.5
    delta: 0.5
    high_freq: 0.5
